# Port dyal had l'microservice (khtar 8084 bach mayw93ch lik conflit m3a les autres services)
server.port=8084

# Nom dyal l'application
spring.application.name=microequipements

# Configuration MySQL
# (createDatabaseIfNotExist=true katkhli Spring Boot yssawb la base de données rasso ila mal9ahach)
spring.datasource.url=jdbc:mysql://localhost:3306/db_equipements?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuration Hibernate / JPA (bach y-creer les tables automatiquement)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true